[platformio]
src_dir = .

[env]
platform = espressif32
board = heltec_wifi_lora_32_V4
framework = arduino

board_build.variants_dir = variants
board_build.variant = heltec_V4

lib_deps =
    thingpulse/ESP8266 and ESP32 OLED driver for SSD1306 displays @ ^4.6.1
    jgromes/RadioLib

monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0

[env:tx]
build_flags =
    -DARGUS_LOCAL_DEVICE_ID=0x01
    -DARGUS_PEER_DEVICE_ID=0x10
build_src_filter =
    +<src-tx/**>
    -<src-rx/**>
upload_port = COM4
monitor_port = COM4

[env:rx]
build_flags =
    -DARGUS_LOCAL_DEVICE_ID=0x10
    -DARGUS_PEER_DEVICE_ID=0x01
build_src_filter =
    +<src-rx/**>
    -<src-tx/**>
upload_port = COM5
monitor_port = COM5
